'use strict';

// 1. CONFIGURATION — set false only when your team's Agent API is running.
const DEMO_MODE = true;
const API_BASE = ''; // Example: http://127.0.0.1:8000 (configure CORS on that server).
const API_TIMEOUT_MS = 120000;
const MAX_FILE_BYTES = 20 * 1024 * 1024;

// 2. ICONS — inline SVG keeps the interface usable without a CDN dependency.
const ICONS = {
  plus:'<path d="M12 5v14M5 12h14"/>',
  history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7m2-5v6l4 2"/>',
  sparkles:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3ZM3 2v4M1 4h4"/>',
  database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',
  'chevron-right':'<path d="m9 5 7 7-7 7"/>',
  'chevron-down':'<path d="m5 9 7 7 7-7"/>',
  settings:'<path d="m9 3-1 3-3 1-2 4 2 2 1 4 4 2 3-1 3 1 4-2 1-4 2-2-2-4-3-1-1-3H9Z"/><circle cx="12" cy="12" r="3"/>',
  menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
  'badge-check':'<path d="m12 2 3 2 4 1 1 4 2 3-2 3-1 4-4 1-3 2-3-2-4-1-1-4-2-3 2-3 1-4 4-1 3-2Z"/><path d="m8 12 3 3 5-6"/>',
  lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>',
  monitor:'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M8 21h8m-4-5v5"/>',
  'panel-right':'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M15 4v16"/>',
  files:'<path d="M8 3h8l4 4v13H8V3Zm8 0v5h4M4 7v16h12"/>',
  file:'<path d="M5 3h9l5 5v13H5V3Zm9 0v6h5M8 13h8m-8 4h6"/>',
  'file-up':'<path d="M5 3h9l5 5v13H5V3Zm9 0v6h5m-7 9v-7m-3 3 3-3 3 3"/>',
  'arrow-up-right':'<path d="m6 18 12-12M6 6h12v12"/>',
  'arrow-up':'<path d="M12 20V4m-6 6 6-6 6 6"/>',
  'arrow-right':'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  play:'<path d="m8 4 12 8-12 8V4Z"/>',
  'shield-check':'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Zm-4 9 3 3 5-6"/>',
  network:'<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="17" width="6" height="5" rx="1"/><rect x="16" y="17" width="6" height="5" rx="1"/><path d="M12 7v5H5v5m7-5h7v5"/>',
  x:'<path d="m6 6 12 12M6 18 18 6"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  circle:'<circle cx="12" cy="12" r="5"/>',
  'check-circle':'<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  compare:'<path d="M7 3v18M17 3v18M3 7l4-4 4 4m2 10 4 4 4-4"/>',
  copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',
  link:'<path d="m9 15 6-6m-5-3 2-2a5 5 0 0 1 7 7l-2 2m-3 5-2 2a5 5 0 0 1-7-7l2-2"/>',
  download:'<path d="M12 3v13m-5-5 5 5 5-5M4 16v5h16v-5"/>',
  stop:'<rect x="6" y="6" width="12" height="12" rx="1"/>',
  message:'<path d="M3 4h18v13H8l-5 4V4Z"/>',
  info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name] || ICONS.file}</svg>`;
const $ = selector => document.querySelector(selector);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
document.querySelectorAll('[data-icon]').forEach(el => { el.innerHTML = icon(el.dataset.icon); });

// 3. EVIDENCE — these particular passages were checked against the supplied DOCX files.
// Other demo findings below are explicitly synthetic. None are produced from user uploads.
const source = (revision, point, text, kind = 'synthetic', highlight = '') => ({
  document:`Положение №${revision}`, filename:`Положение_о_внутреннем_аудите_редакция_${revision}_обезличено.docx`,
  section:point.split('.')[0], point, text, kind, highlight
});
const EVIDENCE = {
  structure8:source(8,'3.4','3.4. БВА состоит из следующих структурных подразделений:\nа. Департамент непрерывного мониторинга системы внутреннего контроля (ДНМ).\nб. Департамент контроля качества аудита и методологии (ДККМ).','verified','Департамент непрерывного мониторинга'),
  structure9:source(9,'3.4','3.4. БВА состоит из следующих структурных подразделений:\nа. Департамент ИТ-аудита и анализа данных (ДИТААД).\nб. Департамент операционного аудита (ДОА).\nв. Департамент непрерывного мониторинга системы внутреннего контроля (ДНМ).\nг. Департамент контроля качества аудита и методологии (ДККМ).','verified','Департамент ИТ-аудита и анализа данных (ДИТААД)'),
  director8:source(8,'3.5','3.5. Главному аудитору подчиняются работники БВА в соответствии со штатным расписанием:\nа. Директор направления внутреннего аудита.\nб. Директор ДНМ.\nв. Директор ДККМ.','verified','Директор направления внутреннего аудита'),
  director9:source(9,'3.5','3.5. Главному аудитору подчиняются работники БВА в соответствии со штатным расписанием:\nа. Директор ДИТААД.\nб. Директор ДОА.\nв. Директор ДНМ.\nг. Директор ДККМ.','verified','Директор ДИТААД'),
  it9:source(9,'5.3.2','5.3.2. организуют по решению Главного аудитора руководство курируемых плановых и внеплановых проверок:\nа. аудит ИТ систем, Информационная безопасность, аудит персональных данных, ИТ-инциденты, непрерывность бизнеса, дата аналитика, применения языков программирования, создание дашбордов, автоматизация процессов ВА (ДИТААД);\nб. аудит процессов развития, операционных и поддерживающих процессов Общества (ДОА).','verified','аудит ИТ систем'),
  reporting8:source(8,'ДЕМО-2.1','Демо: подразделение подготавливает отчет о выполнении корректирующих мероприятий.'),
  archive8:source(8,'ДЕМО-2.2','Демо: подразделение обеспечивает хранение рабочих материалов аудиторских проверок.'),
  training8:source(8,'ДЕМО-2.3','Демо: подразделение организует ежегодное обучение координаторов внутреннего контроля.'),
  riskA9:source(9,'ДЕМО-4.1','Демо: подразделение внутреннего аудита обновляет корпоративный реестр рисков.'),
  riskB9:source(9,'ДЕМО-4.2','Демо: подразделение управления рисками поддерживает в актуальном состоянии корпоративный реестр рисков.'),
  reportA9:source(9,'ДЕМО-4.3','Демо: отдел аудита готовит сводную квартальную отчетность о контрольных мероприятиях.'),
  reportB9:source(9,'ДЕМО-4.4','Демо: отдел контроля готовит сводную квартальную отчетность о контрольных мероприятиях.')
};
function syntheticPair(n, before, after) { return [source(8,`ДЕМО-${n}`,`Демо: ${before}`),source(9,`ДЕМО-${n}`,`Демо: ${after}`)]; }
const DEMO_CHANGES = [
  {id:'A1',type:'added',title:'ДИТААД — ИТ-аудит және деректерді талдау',description:'9-редакцияның 3.4-тармағындағы бөлімшелер тізіміне ДИТААД қосылған. 8-редакцияның осы тізімінде ол жоқ.',sources:[EVIDENCE.structure8,EVIDENCE.structure9],impact:'high'},
  {id:'A2',type:'added',title:'ДОА — операциялық аудит департаменті',description:'ДОА 9-редакцияның құрылымдық бөлімшелер тізімінде көрсетілген. Оның аудит бағыты 5.3.2-тармақта нақтыланған.',sources:[EVIDENCE.structure9,EVIDENCE.it9],impact:'high'},
  {id:'A3',type:'added',title:'Тесттік: бақылау панельдерін дайындау',description:'Жасанды сценарийде жаңа аналитикалық панельдерді әзірлеу функциясы қосылды.',sources:[source(9,'ДЕМО-3.1','Демо: подразделение разрабатывает аналитические панели для контроля результатов аудита.')],impact:'medium'},
  {id:'A4',type:'added',title:'Тесттік: деректер сапасын тексеру',description:'Жасанды сценарийде деректер сапасын жүйелі тексеру міндеті қосылды.',sources:[source(9,'ДЕМО-3.2','Демо: подразделение проводит регулярную проверку качества данных.')],impact:'medium'},
  {id:'A5',type:'added',title:'Тесттік: цифрлық аудит әдістемесі',description:'Жасанды сценарийде цифрлық аудит бойынша әдістемелік қолдау қосылды.',sources:[source(9,'ДЕМО-3.3','Демо: подразделение разрабатывает методическую поддержку цифрового аудита.')],impact:'low'},
  {id:'R1',type:'removed',title:'Тесттік: түзету шараларының орындалу есебі',description:'Шартты кейінгі жинақта осы міндетке сәйкестік табылмады. Басқа бөлімшеге ауысқанын тексеру керек.',sources:[EVIDENCE.reporting8],impact:'medium'},
  {id:'R2',type:'removed',title:'Тесттік: аудит материалдарын мұрағаттау',description:'Жасанды сценарийде мұрағаттау функциясы кейінгі редакцияда көрсетілмеген.',sources:[EVIDENCE.archive8],impact:'medium'},
  {id:'R3',type:'removed',title:'Тесттік: бақылау координаторларын оқыту',description:'Шартты кейінгі нұсқада оқытуға жауапты бөлімше анықталмаған.',sources:[EVIDENCE.training8],impact:'low'},
  {id:'M1',type:'modified',title:'Директор бағытының өзгеруі',description:'Бас аудиторға бағынысты тұлғалар тізімінде «Директор направления внутреннего аудита» орнына ДИТААД пен ДОА директорлары көрсетілген. Ресми рөл бөлінуін бұйрықпен тексеру қажет.',sources:[EVIDENCE.director8,EVIDENCE.director9],impact:'high'},
  {id:'M2',type:'modified',title:'Аудит бағыттары нақтыланған',description:'9-редакцияның 5.3.2-тармағы ИТ-аудитті ДИТААД-қа, ал операциялық процестер аудитін ДОА-ға жатқызады. Бұл функция жоғалды дегенді білдірмейді.',sources:[EVIDENCE.it9],impact:'medium'},
  {id:'M3',type:'modified',title:'Тесттік: есеп беру жиілігі',description:'Жасанды сценарийде есеп беру жиілігі жылдықтан тоқсандыққа өзгерді.',sources:syntheticPair('5.1','Отчет представляется ежегодно.','Отчет представляется ежеквартально.'),impact:'low'},
  {id:'M4',type:'modified',title:'Тесттік: келісу тәртібі',description:'Жасанды сценарийде жоспарды келісетін жауапты рөл өзгерді.',sources:syntheticPair('5.2','План согласует руководитель направления.','План согласует директор департамента.'),impact:'low'},
  {id:'D1',type:'duplicate',title:'Тесттік: тәуекелдер тізілімін жаңарту',description:'Екі шартты бөлімшеге бір тізілімді жаңарту міндеті берілген. 87% — демонстрациялық ұқсастық бағасы.',sources:[EVIDENCE.riskA9,EVIDENCE.riskB9],similarity:87,impact:'medium'},
  {id:'D2',type:'duplicate',title:'Тесттік: бақылау нәтижелері бойынша есеп',description:'Шартты аудит және бақылау бөлімшелері бірдей жиынтық есеп дайындайды. Жауапкершілікті нақтылау қажет.',sources:[EVIDENCE.reportA9,EVIDENCE.reportB9],similarity:91,impact:'medium'}
];
const DEMO_RESULT = {
  answer:'№8 және №9 редакцияларын салыстырудың демо сценарийінде 14 маңызды өзгеріс көрсетілген.',
  sources:[EVIDENCE.structure9], changes:DEMO_CHANGES, functions_detected:47, confidence:96,
  summary:'Нақты үзінділерде ДИТААД пен ДОА бөлімшелер тізіміне қосылған және басшылық тізімі өзгерген. Қалған тесттік тұжырымдар интерфейсті көрсетуге арналған. Қорытындыны жауапты қызметкер тексеруі тиіс.'
};
const TYPE_LABELS = {added:'Жаңа функция',removed:'Жоғалу қаупі',modified:'Өзгерген функция',duplicate:'Ықтимал қайталану'};
// 4. NEURAL WORKSPACE — UI state, demo runner and real API boundary.
ICONS.pause = '<path d="M8 5v14M16 5v14"/>';
const TYPE_META = {
  added:{color:'#00e5c3',icon:'plus',label:'NEW FUNCTIONS',prefix:'+'},
  removed:{color:'#ff7e98',icon:'x',label:'MISSING FUNCTIONS',prefix:'−'},
  modified:{color:'#4cb8ff',icon:'compare',label:'TRANSFORMED',prefix:'↻'},
  duplicate:{color:'#efbe6a',icon:'copy',label:'OVERLAPS',prefix:'≈'}
};
const NEURAL_TOOLS = [
  ['Document Parser','file','Құжаттар құрылымы оқылды'],
  ['Structure Mapper','network','Бөлімшелер сәйкестендірілді'],
  ['Function Extractor','database','47 функция анықталды'],
  ['Semantic Engine','sparkles','1 184 байланыс тексерілді'],
  ['Duplicate Detector','copy','2 ықтимал қайталану'],
  ['Source Verifier','shield-check','14 тұжырымның сілтемелері дайын']
];
const state = {files:{a:null,b:null},scans:{a:0,b:0},result:null,sessionId:null,busy:false,controller:null,generation:0,filter:'all',logs:[],motion:!matchMedia('(prefers-reduced-motion: reduce)').matches,presentation:false};
let toastTimer, paletteIndex=0, visibleCommands=[], graphFrame=0, evidenceController=null;
const root = $('#command-center');
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function openDialog(id){const el=$(id);if(!el.open)el.showModal();}
function activity(message){state.logs.push({time:new Date().toLocaleTimeString('kk-KZ',{hour12:false}),message});state.logs=state.logs.slice(-6);$('#activity-timeline').innerHTML=state.logs.map(log=>`<div class="activity-entry"><span>✓</span><div><time>${escapeHTML(log.time)}</time><p>${escapeHTML(log.message)}</p></div></div>`).join('');$('#activity-timeline').scrollLeft=$('#activity-timeline').scrollWidth;}
function status(mode,text){root.dataset.state=mode;$('#core-status').textContent=text;$('#stage-mode').textContent=({idle:'STANDBY',loaded:'CONNECTED',analyzing:'PROCESSING',complete:'EXPLORE MODE',error:'ATTENTION'})[mode]||mode;}
function delay(ms,signal){return new Promise((resolve,reject)=>{if(signal?.aborted)return reject(new DOMException('Aborted','AbortError'));const cancel=()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));};const timer=setTimeout(()=>{signal?.removeEventListener('abort',cancel);resolve();},ms);signal?.addEventListener('abort',cancel,{once:true});});}
function setBusy(value){state.busy=value;$('#ask-button').disabled=value;$('#demo-button').disabled=value;$('#file-a').disabled=value;$('#file-b').disabled=value;$('#analyze-button').disabled=value||!state.files.a||!state.files.b||Boolean(state.scans.a||state.scans.b);$('#restore-session').disabled=value;}
function updateReady(){const count=Number(Boolean(state.files.a))+Number(Boolean(state.files.b));root.classList.toggle('documents-ready',count===2);$('#connection-status').innerHTML=`${count} DOCUMENTS CONNECTED <span>•</span> ${count===2?'READY FOR ANALYSIS':'WAITING FOR INPUT'}`;setBusy(state.busy);if(!state.busy&&!state.result)status(count?'loaded':'idle',count===2?'READY FOR ANALYSIS':'IDLE · AWAITING INPUT');}
function renderDNA(side,loaded=false){$('#dna-'+side).innerHTML=Array.from({length:37},(_,i)=>`<i style="height:${loaded?5+((i*17+(side==='a'?7:13))%27):2+((i*7)%9)}px;opacity:${.35+((i*13)%65)/100}"></i>`).join('');$('#dna-'+side).style.opacity=loaded?'.9':'.4';}
function clearResults(){state.result=null;state.sessionId=null;root.classList.remove('exploring','source-map');$('#neural-graph').hidden=true;$('#intelligence-signals').hidden=true;$('#core-controls').hidden=false;$('#analysis-progress').hidden=true;$('#graph-nodes').innerHTML='';$('#graph-connections').innerHTML='';$('#report-button').disabled=true;$('#readiness-confidence').textContent='—';$('#readiness-sources').textContent='—';$('#relationships-label').textContent='SEMANTIC RELATIONSHIPS / STANDBY';$('#tool-orbit').innerHTML='';state.filter='all';renderFilters();}
async function attachDocument(side,file,isExample=false){
  if(state.busy)return toast('Алдымен ағымдағы операцияның аяқталуын күтіңіз.');
  if(!file||!/\.(pdf|docx|xlsx)$/i.test(file.name))return toast('PDF, DOCX немесе XLSX файлын таңдаңыз.');
  if(file.size>MAX_FILE_BYTES)return toast('Файл көлемі 20 MB-тан аспауы керек.');
  if(file.size===0)return toast('Бос файлды жүктеу мүмкін емес.');
  clearResults();state.files[side]=file;const token=Date.now()+Math.random();state.scans[side]=token;const epoch=state.generation;
  $('#name-'+side).textContent=isExample?`Положение · редакция ${side==='a'?'08':'09'}`:file.name;
  $('#meta-'+side).textContent=isExample?'Алдын ала дайындалған №8 → №9 сценарийі':`${(file.size/1024).toFixed(1)} KB · ${DEMO_MODE?'демо: мазмұны оқылмайды':'жіберуге дайын'}`;
  $('#choose-'+side).innerHTML=`Құжатты ауыстыру${icon('plus')}`;$('#module-'+side).classList.add('loaded');renderDNA(side,true);updateReady();
  if(DEMO_MODE){$('#module-'+side).classList.add('scanning');for(const step of ['DEMO · READING DOCUMENT','DEMO · DETECTING STRUCTURE','DEMO · EXTRACTING FUNCTIONS']){if(state.scans[side]!==token||epoch!==state.generation)return;$('#status-'+side).textContent=step;await delay(320);}}
  if(state.scans[side]!==token||epoch!==state.generation)return;
  state.scans[side]=0;$('#module-'+side).classList.remove('scanning');$('#status-'+side).textContent=DEMO_MODE?'DEMO · DOCUMENT UNDERSTOOD':'FILE READY FOR UPLOAD';activity(`${DEMO_MODE?'Демо · ':''}Document ${side.toUpperCase()} қосылды`);updateReady();
}
function resetSession(){state.controller?.abort();evidenceController?.abort();state.controller=null;state.generation++;state.scans={a:0,b:0};state.files={a:null,b:null};state.logs=[];setBusy(false);clearResults();['a','b'].forEach(side=>{$('#file-'+side).value='';$('#name-'+side).textContent=side==='a'?'Бастапқы редакция':'Жаңартылған редакция';$('#meta-'+side).textContent='Құжатты қосыңыз немесе осында сүйреңіз';$('#choose-'+side).innerHTML=`Файлды таңдау${icon('plus')}`;$('#status-'+side).textContent='AWAITING DOCUMENT';$('#module-'+side).classList.remove('loaded','scanning');renderDNA(side);});document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('#session-label').textContent='001';$('#agent-input').value='';updateReady();activity('Жаңа сессия · құжаттарды қосыңыз');}

// Every real request is cancellable and fails visibly; it never substitutes demo data.
async function api(path,{method='GET',body,signal}={}){
  const controller=new AbortController();let timedOut=false;const abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)controller.abort();
  const timer=setTimeout(()=>{timedOut=true;controller.abort();},API_TIMEOUT_MS);
  try{const response=await fetch(API_BASE+path,{method,body:body instanceof FormData?body:body===undefined?undefined:JSON.stringify(body),headers:body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:undefined,signal:controller.signal});if(!response.ok)throw new Error(`API ${response.status}: ${response.statusText||'сұрау орындалмады'}`);return await response.json();}
  catch(error){if(timedOut)throw new Error('Сервер жауап бермеді. 120 секунд күту шегі аяқталды.');throw error;}
  finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}
}
function normalizeSource(s){return{document:String(s?.document||s?.filename||'Құжат'),filename:String(s?.filename||''),point:String(s?.point||''),text:String(s?.text||s?.quote||''),highlight:String(s?.highlight||''),kind:DEMO_MODE&&s?.kind==='verified'?'verified':DEMO_MODE?'synthetic':'backend',side:s?.side==='before'||s?.side==='after'?s.side:null};}
function percent(value){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=100?value:null;}
function normalizeResult(data){const r=data?.result||data;if(!r||!Array.isArray(r.changes))throw new Error('API жауабында changes массиві жоқ.');const ids=new Set();return{summary:String(r.summary||r.answer||'Талдау аяқталды.'),answer:String(r.answer||''),confidence:percent(r.confidence),functions_detected:Number.isInteger(r.functions_detected)?r.functions_detected:null,changes:r.changes.map((c,i)=>{const id=String(c.id??`change-${i+1}`);if(ids.has(id))throw new Error('API changes ішінде қайталанған id бар.');ids.add(id);if(!TYPE_META[c.type])throw new Error('API белгісіз өзгеріс түрін қайтарды.');return{id,type:c.type,title:String(c.title||'Өзгеріс'),description:String(c.description||''),sources:Array.isArray(c.sources)?c.sources.map(normalizeSource):[],impact:String(c.impact||''),similarity:percent(c.similarity),confidence:percent(c.confidence),evidence_id:c.evidence_id?String(c.evidence_id):null};})};}
function setProgress(value,label){$('#analysis-fill').style.width=value+'%';$('#analysis-percent').textContent=value===null?'…':value+'%';$('#analysis-phase').textContent=label;}
async function analyze(){
  if(state.busy)return;if(!state.files.a||!state.files.b||state.scans.a||state.scans.b)return toast('Екі құжатты қосып, дайын болғанын күтіңіз.');
  clearResults();const epoch=state.generation;const controller=new AbortController();state.controller=controller;setBusy(true);status('analyzing',DEMO_MODE?'DEMO · NEURAL ENGINE ACTIVE':'AGENT API · PROCESSING');$('#core-controls').hidden=true;$('#analysis-progress').hidden=false;setProgress(DEMO_MODE?0:null,DEMO_MODE?'DEMO SIMULATION':'UPLOADING DOCUMENTS');activity(DEMO_MODE?'Демо талдау басталды':'Құжаттар серверге жіберілуде');
  try{let result;
    if(DEMO_MODE){$('#tool-orbit').innerHTML=NEURAL_TOOLS.map(([name,glyph],i)=>`<div class="tool-node" id="tool-${i}">${icon(glyph)}<span>${name}</span></div>`).join('');for(let i=0;i<NEURAL_TOOLS.length;i++){$('#tool-'+i).classList.add('active');setProgress(Math.round(i/6*100),'DEMO · '+NEURAL_TOOLS[i][0].toUpperCase());await delay(650,controller.signal);$('#tool-'+i).classList.replace('active','done');activity('Демо · '+NEURAL_TOOLS[i][2]);}setProgress(100,'INTELLIGENCE READY');await delay(250,controller.signal);result=normalizeResult(DEMO_RESULT);state.sessionId='demo-local';}
    else{const body=new FormData();body.append('old_document',state.files.a);body.append('new_document',state.files.b);const upload=await api('/api/documents',{method:'POST',body,signal:controller.signal});if(!upload.session_id)throw new Error('API session_id қайтармады.');state.sessionId=String(upload.session_id);setProgress(null,'AGENT API · ANALYZING');activity('Сервер құжаттарды қабылдады');result=normalizeResult(await api('/api/analyze',{method:'POST',body:{session_id:state.sessionId},signal:controller.signal}));}
    if(epoch!==state.generation)return;state.result=result;showResult();activity(`${DEMO_MODE?'Демо · ':''}${result.changes.length} өзгеріс · карта дайын`);
  }catch(error){if(epoch!==state.generation)return;$('#core-controls').hidden=false;$('#analysis-progress').hidden=true;$('#tool-orbit').innerHTML='';if(error.name==='AbortError'){status('loaded','CANCELLED · READY TO RETRY');activity('Күту тоқтатылды');toast(DEMO_MODE?'Демо тоқтатылды.':'Күту тоқтатылды. Сервер тапсырманы жалғастыруы мүмкін.');}else{status('error','REQUEST FAILED');toast(error.message);activity('Қате · '+error.message);}}
  finally{if(epoch===state.generation){state.controller=null;setBusy(false);}}
}
function showResult(){root.classList.add('exploring');$('#core-controls').hidden=true;$('#analysis-progress').hidden=true;$('#neural-graph').hidden=false;$('#intelligence-signals').hidden=false;$('#report-button').disabled=false;$('#session-label').textContent=state.sessionId==='demo-local'?'DEMO / 001':state.sessionId||'001';$('#readiness-confidence').textContent=state.result.confidence===null?'NOT PROVIDED':`${state.result.confidence}%${DEMO_MODE?' · DEMO':''}`;const sourceCount=state.result.changes.filter(c=>c.sources.length||c.evidence_id).length;$('#readiness-sources').textContent=`${sourceCount}/${state.result.changes.length} ${DEMO_MODE?'· DEMO':''}`;$('#relationships-label').textContent=DEMO_MODE?'1 184 RELATIONSHIPS / DEMO SIMULATION':`${state.result.changes.length} CHANGE NODES / API RESULT`;status('complete',DEMO_MODE?'DEMO · INTELLIGENCE READY':'ANALYSIS COMPLETE');renderSignals();renderGraph();setFilter('all');}
function renderSignals(){const changes=state.result?.changes||[];$('#intelligence-signals').innerHTML=Object.entries(TYPE_META).map(([key,m])=>`<button class="signal" data-filter="${key}" style="--node-color:${m.color}" aria-label="${TYPE_LABELS[key]}"><strong>${m.prefix}${String(changes.filter(c=>c.type===key).length).padStart(2,'0')}</strong><span>${m.label}${DEMO_MODE?' · DEMO':''}</span></button>`).join('');}
function renderFilters(){const items=[['all','ALL'],['added','NEW'],['removed','LOST'],['modified','TRANSFORMED'],['duplicate','OVERLAPS'],['sources','SOURCE MAP']];$('#map-filters').innerHTML=items.map(([key,label])=>`<button class="filter-button ${state.filter===key?'active':''}" data-filter="${key}" aria-pressed="${state.filter===key}" ${TYPE_META[key]?`style="--node-color:${TYPE_META[key].color}"`:''}>${TYPE_META[key]?'<i></i>':''}${label}</button>`).join('');}
function renderGraph(){
  const graph=$('#neural-graph'),w=graph.clientWidth,h=graph.clientHeight;if(!w||!h||!state.result)return;
  const changes=state.result.changes;const before=changes.filter(c=>c.type==='removed'||c.type==='modified'),after=changes.filter(c=>c.type==='added'||c.type==='duplicate');
  // Large API results remain accessible with a scrollable graph; keep a readable row height.
  const rowHeight=innerWidth>900&&innerHeight<=850?37:49;
  const rows=Math.max(before.length,after.length,1),contentHeight=Math.max(h,rows*rowHeight+15);graph.style.overflowY=contentHeight>h?'auto':'visible';const nodes=$('#graph-nodes');nodes.style.height=contentHeight+'px';const svg=$('#graph-connections');svg.setAttribute('viewBox',`0 0 ${w} ${contentHeight}`);svg.style.height=contentHeight+'px';
  let markup='',paths='';[[before,false],[after,true]].forEach(([list,right])=>list.forEach((c,index)=>{const m=TYPE_META[c.type],y=14+index*((contentHeight-57)/Math.max(rows-1,1)),nodeW=w*(w<400?.32:.29),start=right?w-nodeW:nodeW,end=right?w/2+35:w/2-35,mid=(start+end)/2;markup+=`<button class="graph-node" data-change="${escapeHTML(c.id)}" style="${right?'right':'left'}:0;top:${y}px;--node-color:${m.color}" title="${escapeHTML(c.title)}" aria-label="${escapeHTML(c.title)} — Source Trace">${icon(m.icon)}<span><small>${escapeHTML(c.id)} / ${m.label}</small>${escapeHTML(c.title.replace('Тесттік: ',''))}</span></button>`;paths+=`<path data-change="${escapeHTML(c.id)}" style="--node-color:${m.color}" d="M${start} ${y+19} C${mid} ${y+19},${mid} ${Math.min(h*.44,210)},${end} ${Math.min(h*.44,210)}"/>`;}));nodes.innerHTML=markup||'<p class="trace-empty">Өзгерістер анықталған жоқ.</p>';svg.innerHTML=paths;applyFilter();
}
function setFilter(value){state.filter=value;root.classList.toggle('source-map',value==='sources');renderFilters();applyFilter();document.querySelectorAll('.signal').forEach(b=>b.classList.toggle('active',b.dataset.filter===value));}
function applyFilter(ids=null){const changes=state.result?.changes||[];document.querySelectorAll('[data-change]').forEach(el=>{const c=changes.find(item=>item.id===el.dataset.change);if(!c)return;const active=ids?ids.includes(c.id):state.filter==='all'||state.filter==='sources'||c.type===state.filter;el.classList.toggle('dimmed',!active);el.classList.toggle('selected',Boolean(ids&&active));});}
function sourceMarkup(s){let quote=escapeHTML(s.text);if(s.highlight)quote=quote.split(escapeHTML(s.highlight)).join(`<mark>${escapeHTML(s.highlight)}</mark>`);return`<article class="evidence-block"><strong>${escapeHTML(s.document)}${s.point?' · § '+escapeHTML(s.point):''}</strong><small>${escapeHTML(s.filename)}</small><p>${quote||'Мәтін үзіндісі берілмеген.'}</p><small class="source-kind ${s.kind==='synthetic'?'synthetic':''}">${s.kind==='verified'?'✓ Бастапқы DOCX-пен тексерілген үзінді':s.kind==='synthetic'?'ДЕМО · жасанды сценарий үзіндісі':'API дереккөзі · бастапқы құжатпен тексеріңіз'}</small></article>`;}
function sourceSide(s){if(s.side)return s.side;if(/№8|редакция_8|редакция 8|original|before/i.test(s.document+' '+s.filename))return'before';if(/№9|редакция_9|редакция 9|revised|after/i.test(s.document+' '+s.filename))return'after';return'other';}
async function showTrace(id){const c=state.result?.changes.find(item=>item.id===id);if(!c)return;applyFilter([id]);openDialog('#source-trace');$('#trace-title').textContent='SOURCE TRACE / '+id;$('#trace-content').innerHTML='<div class="insight-loading">Дереккөздер ашылуда…</div>';evidenceController?.abort();const ctrl=new AbortController();evidenceController=ctrl;
  try{let sources=c.sources;if(!DEMO_MODE&&c.evidence_id){const data=await api('/api/evidence/'+encodeURIComponent(c.evidence_id),{signal:ctrl.signal});if(!Array.isArray(data.sources))throw new Error('Evidence API sources массивін қайтармады.');sources=data.sources.map(normalizeSource);}if(ctrl.signal.aborted)return;
  c.sources=sources;const before=sources.filter(s=>sourceSide(s)==='before'),after=sources.filter(s=>sourceSide(s)==='after'),other=sources.filter(s=>sourceSide(s)==='other');const confidence=c.confidence??state.result.confidence;
  $('#trace-content').innerHTML=`<div class="trace-summary"><h3>${escapeHTML(c.title)}</h3><p>${escapeHTML(c.description)}</p><div class="evidence-tags"><span>${escapeHTML(TYPE_LABELS[c.type])}</span>${confidence!==null?`<span>${DEMO_MODE?'DEMO ':''}CONFIDENCE ${confidence}%</span>`:''}${c.similarity!==null&&c.similarity!==undefined?`<span>${DEMO_MODE?'DEMO ':''}SEMANTIC MATCH ${c.similarity}%</span>`:''}<span>${sources.length} SOURCE REFERENCES</span></div></div><div class="trace-grid"><section class="trace-column"><h4>DOCUMENT A / BEFORE</h4>${before.map(sourceMarkup).join('')||'<p class="trace-empty">Бұл тұжырым үшін бастапқы нұсқаның үзіндісі берілмеген.</p>'}</section><section class="trace-column"><h4>DOCUMENT B / AFTER</h4>${after.map(sourceMarkup).join('')||'<p class="trace-empty">Кейінгі нұсқаның сәйкестігі берілмеген. Бұл функцияның жоғалғанын өздігінен дәлелдемейді.</p>'}</section>${other.length?`<section class="trace-column"><h4>OTHER SOURCES / VERSION UNSPECIFIED</h4>${other.map(sourceMarkup).join('')}</section>`:''}</div>`;$('#trace-disclaimer').textContent=DEMO_MODE?'Демо: көрсеткіштер симуляция. «Тесттік» тұжырымдар мен ДЕМО тармақтары нақты құжаттың қорытындысы емес.':'Әр тұжырымды бастапқы құжатпен тексеріңіз. Confidence — сервер көрсеткіші.';
  }catch(error){if(error.name!=='AbortError')$('#trace-content').innerHTML=`<div class="insight-body"><p>${escapeHTML(error.message)}</p></div>`;}
}

// 5. AGENT INSIGHTS — a focused overlay, not a chat transcript.
function demoInsight(question){const q=question.toLowerCase();let ids,answer;if(/дитаад|it.audit|ит.аудит/.test(q)){ids=['A1','M1','M2'];answer='ДИТААД 9-редакцияның 3.4-тармағында құрылымдық бөлімше ретінде көрсетілген. 3.5-тармақта ДИТААД директоры Бас аудиторға бағынады. 5.3.2-тармақта ИТ-аудит пен деректерді талдау бағыттары нақтыланған.\n\nДиректор рөлінің ресми бөлінуін тиісті бұйрықпен тексеру керек.';}else if(/доа/.test(q)){ids=['A2','M1','M2'];answer='ДОА 9-редакцияның 3.4-тармағына енгізілген. 5.3.2-тармақ бойынша оған даму, операциялық және қолдау процестерінің аудиті жатқызылған.';}else if(/жоғал|missing|lost|утрач/.test(q)){ids=['R1','R2','R3'];answer='Демо сценарийде 3 жоғалу қаупі бар: түзету шараларының есебі, материалдарды мұрағаттау және координаторларды оқыту.\n\nБұлар — интерфейсті көрсетуге арналған жасанды тұжырымдар. Жүктелген файлдар талданған жоқ.';}else if(/қайтал|duplicate|overlap|дубли/.test(q)){ids=['D1','D2'];answer='Демо сценарийде 2 ықтимал қайталану көрсетілген: тәуекелдер тізілімін жаңарту және бақылау нәтижелері бойынша есеп. 87% пен 91% — жасанды ұқсастық көрсеткіштері. Нақты жауапкершіліктерді backend талдауы анықтауы керек.';}else if(/жаңа|new|added|нов/.test(q)){ids=['A1','A2','A3','A4','A5'];answer='Картада 5 жаңа функция сигналы бар. ДИТААД пен ДОА — берілген құжаттың 3.4-тармағымен тексерілген құрылымдық өзгерістер. Қалған 3 сигнал — жасанды демо мысалдары.';}else if(/салыстыр|өзгер|құрылым|директор|compare|transform|structure/.test(q)){ids=['M1','M2','M3','M4','A1','A2'];answer='№8 → №9: 3.4-тармақтың бөлімшелер тізіміне ДИТААД пен ДОА қосылған. 3.5-тармақта «Директор направления внутреннего аудита» орнына екі департамент директоры көрсетілген.\n\nКартадағы есеп жиілігі мен келісу тәртібі туралы тұжырымдар — тесттік. M1 түйінінен екі редакцияның нақты үзіндісін қатар ашыңыз.';}else{ids=[];answer='Бұл демо алдын ала дайындалған №8 → №9 сценарийімен жұмыс істейді. «ДИТААД», «Жоғалған функциялар», «Қайталанулар» немесе «Құрылымды салыстыр» деп сұраңыз. Еркін сұрақтарға нақты жауап беру үшін Agent API қосылуы қажет.';}return{answer,highlight_change_ids:ids,sources:[]};}
async function askAgent(question){question=question.trim();if(!question)return;if(state.busy)return toast('Агент ағымдағы операцияны аяқтағанша күтіңіз.');if(!state.result)return toast('Алдымен екі құжатты қосып, талдауды іске қосыңыз.');if(/^(толық )?есеп( жаса)?$/i.test(question))return showReport();const controller=new AbortController(),epoch=state.generation;state.controller=controller;setBusy(true);openDialog('#insight-dialog');$('#insight-content').innerHTML='<div class="insight-loading">Агент дереккөздерді байланыстыруда…</div>';status('analyzing',DEMO_MODE?'DEMO · AGENT INSIGHT':'AGENT API · THINKING');
  try{let data;if(DEMO_MODE){await delay(700,controller.signal);data=demoInsight(question);}else data=await api('/api/agent',{method:'POST',body:{session_id:state.sessionId,message:question},signal:controller.signal});if(epoch!==state.generation)return;if(typeof data.answer!=='string')throw new Error('Agent API answer мәтінін қайтармады.');const ids=Array.isArray(data.highlight_change_ids)?data.highlight_change_ids.map(String).filter(id=>state.result.changes.some(c=>c.id===id)):[];applyFilter(ids.length?ids:null);const sources=Array.isArray(data.sources)?data.sources.map(normalizeSource):[];$('#insight-content').innerHTML=`<div class="insight-body"><span class="eyebrow mono">${DEMO_MODE?'DEMO SCENARIO':'AGENT RESPONSE'}</span><p class="insight-question">${escapeHTML(question)}</p><p>${escapeHTML(data.answer)}</p><div class="insight-links">${ids.map(id=>{const c=state.result.changes.find(c=>c.id===id);return`<button data-trace="${escapeHTML(id)}">${icon('link')}${escapeHTML(id+' · '+c.title)}</button>`;}).join('')}</div>${sources.map(sourceMarkup).join('')}<div class="insight-links"><button data-question="ДИТААД туралы түсіндір">ДИТААД</button><button data-question="Жоғалған функцияларды көрсет">Жоғалу қаупі</button><button data-question="Қайталануларды тап">Қайталанулар</button></div></div>`;$('#agent-input').value='';activity(`${DEMO_MODE?'Демо · ':''}Agent Insight · ${ids.length} байланыс`);
  }catch(error){if(epoch!==state.generation)return;$('#insight-content').innerHTML=`<div class="insight-body"><p>${escapeHTML(error.name==='AbortError'?'Сұрау тоқтатылды.':error.message)}</p></div>`;}
  finally{if(epoch===state.generation){state.controller=null;setBusy(false);status('complete',DEMO_MODE?'DEMO · INTELLIGENCE READY':'ANALYSIS COMPLETE');}}
}

// 6. REPORT EXPORT — same evidence used in UI, JSON, CSV and printable PDF.
function reportPayload(){return{mode:DEMO_MODE?'demo':'api',generated_at:new Date().toISOString(),session_id:state.sessionId,documents:{before:state.files.a?.name||null,after:state.files.b?.name||null},notice:DEMO_MODE?'Демо №8 → №9. Таңдалған файлдар өңделмейді. Метрикалар мен тесттік тұжырымдар — симуляция.':'AI тұжырымдарын бастапқы құжатпен тексеріңіз.',...state.result};}
function showReport(){if(!state.result)return toast('Алдымен талдауды іске қосыңыз.');$('#report-content').innerHTML=`<p>${escapeHTML(reportPayload().notice)}</p><p>${escapeHTML(state.result.summary)}</p>${state.result.changes.map(c=>`<div class="report-row"><span>${escapeHTML(TYPE_LABELS[c.type])}</span><strong>${escapeHTML(c.title)}</strong><button data-trace="${escapeHTML(c.id)}">${escapeHTML(c.id)} ↗</button></div>`).join('')}`;openDialog('#report-dialog');}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);activity(name+' экспортталды');}
function csvCell(value){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return'"'+s.replace(/"/g,'""')+'"';}
function exportReport(format){if(!state.result)return;if(format==='json')return download('kt-neural-report.json',JSON.stringify(reportPayload(),null,2),'application/json;charset=utf-8');if(format==='csv'){const rows=[['Режим','ID','Түрі','Тұжырым','Түсіндірме','Дереккөздер'],...state.result.changes.map(c=>[DEMO_MODE?'DEMO':'API',c.id,TYPE_LABELS[c.type],c.title,c.description,c.sources.map(s=>`${s.document} §${s.point}: ${s.text}`).join('\n')])];return download('kt-neural-report.csv','\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
  const win=window.open('','_blank');if(!win)return toast('Браузер жаңа терезені бұғаттады. PDF үшін popup ашуға рұқсат беріңіз.');win.document.open();win.document.write(`<!doctype html><html lang="kk"><head><meta charset="utf-8"><title>KT Neural — қорытынды</title><style>body{font:13px Arial,sans-serif;line-height:1.7;color:#13243b;max-width:900px;margin:40px auto;padding:0 25px}h1{font-size:26px}h2{font-size:16px}article{border-top:1px solid #ccd6df;padding:16px 0;break-inside:avoid}blockquote{border-left:3px solid #08a8c9;margin:10px 0;padding:8px 16px;background:#f0f7f9;white-space:pre-line}small{color:#536980}button{padding:12px 18px;cursor:pointer}@media print{button{display:none}body{margin:0;font-size:11px}@page{margin:18mm}}</style></head><body><button id="print">PDF сақтау / Басып шығару</button><h1>KT NEURAL / Аналитикалық қорытынды</h1><p>${escapeHTML(reportPayload().notice)}</p><p>${escapeHTML(state.result.summary)}</p>${state.result.changes.map(c=>`<article><small>${escapeHTML(c.id+' · '+TYPE_LABELS[c.type])}</small><h2>${escapeHTML(c.title)}</h2><p>${escapeHTML(c.description)}</p>${c.sources.map(s=>`<small>${escapeHTML(s.document+' § '+s.point)} · ${escapeHTML(s.kind==='synthetic'?'ДЕМО ҮЗІНДІ':s.kind==='verified'?'Тексерілген үзінді':'API үзіндісі')}</small><blockquote>${escapeHTML(s.text)}</blockquote>`).join('')}${!c.sources.length?'<small>Үзінді берілмеген. Source Trace арқылы сервер дереккөзін ашыңыз.</small>':''}</article>`).join('')}</body></html>`);win.document.close();win.document.getElementById('print').addEventListener('click',()=>win.print());activity('PDF басып шығару терезесі ашылды');}

// 7. COMMAND PALETTE, SETTINGS AND INPUTS.
const PALETTE_COMMANDS=[
  {label:'Analyze documents',detail:'Құжаттарды талдау',glyph:'sparkles',run:analyze},
  {label:'Find new functions',detail:'Жаңа функциялар',glyph:'plus',run:()=>setFilter('added')},
  {label:'Find missing functions',detail:'Жоғалған функциялар',glyph:'search',run:()=>setFilter('removed')},
  {label:'Detect duplicates',detail:'Қайталанулар',glyph:'copy',run:()=>setFilter('duplicate')},
  {label:'Show transformations',detail:'Өзгерістер',glyph:'compare',run:()=>setFilter('modified')},
  {label:'Trace sources',detail:'Дереккөздерді ашу',glyph:'link',run:()=>state.result?showTrace(state.result.changes.find(c=>c.id==='M1')?.id||state.result.changes[0]?.id):toast('Алдымен талдауды іске қосыңыз.')},
  {label:'Generate report',detail:'Есеп дайындау',glyph:'download',run:showReport},
  {label:'Ask the agent',detail:'Агентке сұрақ қою',glyph:'message',run:()=>$('#agent-input').focus()}
];
function renderPalette(){const q=$('#palette-search').value.toLowerCase();visibleCommands=PALETTE_COMMANDS.filter(c=>(c.label+' '+c.detail).toLowerCase().includes(q));paletteIndex=Math.min(paletteIndex,Math.max(0,visibleCommands.length-1));$('#palette-options').innerHTML=visibleCommands.map((c,i)=>`<button class="command-option ${i===paletteIndex?'selected':''}" data-command="${i}">${icon(c.glyph)}<span>${escapeHTML(c.label)}</span><span>${escapeHTML(c.detail)}</span></button>`).join('')||'<p class="trace-empty" style="padding:15px">Команда табылмады.</p>';}
function openPalette(){paletteIndex=0;$('#palette-search').value='';renderPalette();openDialog('#palette-dialog');$('#palette-search').focus();}
function runCommand(index){const cmd=visibleCommands[index];if(!cmd)return;$('#palette-dialog').close();if(/Find|Detect|Show/.test(cmd.label)&&!state.result)return toast('Алдымен құжаттарды талдаңыз.');cmd.run();}
function setMotion(value){state.motion=value;root.classList.toggle('no-motion',!value);$('#motion-setting').checked=value;$('#motion-toggle').setAttribute('aria-pressed',String(!value));$('#motion-toggle').setAttribute('aria-label',value?'Анимацияны тоқтату':'Анимацияны қосу');$('#motion-toggle').innerHTML=icon(value?'pause':'play');}
function setPresentation(value){state.presentation=value;root.classList.toggle('presentation',value);$('#presentation-button').setAttribute('aria-pressed',String(value));$('#presentation-setting').checked=value;requestAnimationFrame(renderGraph);}
['a','b'].forEach(side=>{$('#file-'+side).addEventListener('change',e=>{if(e.target.files[0])attachDocument(side,e.target.files[0]);});const label=$(`.document-drop[data-side="${side}"]`);label.addEventListener('dragover',e=>{e.preventDefault();$('#module-'+side).classList.add('dragover');});label.addEventListener('dragleave',()=>$('#module-'+side).classList.remove('dragover'));label.addEventListener('drop',e=>{e.preventDefault();$('#module-'+side).classList.remove('dragover');if(e.dataTransfer.files[0])attachDocument(side,e.dataTransfer.files[0]);});});
$('#demo-button').addEventListener('click',async()=>{if(!DEMO_MODE)return toast('Демо үшін script.js ішінде DEMO_MODE = true орнатыңыз.');resetSession();await Promise.all(['a','b'].map(side=>attachDocument(side,{name:`Положение_редакция_${side==='a'?8:9}.docx`,size:24000},true)));toast('Демо құжаттар қосылды. INITIATE INTELLIGENCE түймесін басыңыз.');});
$('#reset-button').addEventListener('click',resetSession);$('#brand').addEventListener('click',e=>{e.preventDefault();setFilter('all');});$('#analyze-button').addEventListener('click',analyze);$('#cancel-analysis').addEventListener('click',()=>state.controller?.abort());$('#agent-form').addEventListener('submit',e=>{e.preventDefault();askAgent($('#agent-input').value);});$('#report-button').addEventListener('click',showReport);['json','csv','pdf'].forEach(format=>$('#export-'+format).addEventListener('click',()=>exportReport(format)));
$('#palette-button').addEventListener('click',openPalette);$('#dock-palette').addEventListener('click',openPalette);$('#palette-search').addEventListener('input',()=>{paletteIndex=0;renderPalette();});$('#palette-search').addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();paletteIndex=(paletteIndex+(e.key==='ArrowDown'?1:-1)+visibleCommands.length)%Math.max(visibleCommands.length,1);renderPalette();$(`.command-option[data-command="${paletteIndex}"]`)?.scrollIntoView({block:'nearest'});}if(e.key==='Enter'){e.preventDefault();runCommand(paletteIndex);}});
$('#settings-button').addEventListener('click',()=>openDialog('#settings-dialog'));$('#motion-setting').addEventListener('change',e=>setMotion(e.target.checked));$('#motion-toggle').addEventListener('click',()=>setMotion(!state.motion));$('#presentation-button').addEventListener('click',()=>setPresentation(!state.presentation));$('#presentation-setting').addEventListener('change',e=>setPresentation(e.target.checked));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#palette-dialog').open?$('#palette-dialog').close():openPalette();}});
document.addEventListener('click',e=>{const close=e.target.closest('.close-dialog');if(close)close.closest('dialog').close();const command=e.target.closest('[data-command]');if(command)runCommand(Number(command.dataset.command));const filter=e.target.closest('[data-filter]');if(filter){if(!state.result)return toast('Картаны зерттеу үшін талдауды бастаңыз.');setFilter(filter.dataset.filter);}const change=e.target.closest('button[data-change]');if(change)showTrace(change.dataset.change);const trace=e.target.closest('[data-trace]');if(trace)showTrace(trace.dataset.trace);const question=e.target.closest('[data-question]');if(question)askAgent(question.dataset.question);});
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}}));$('#source-trace').addEventListener('close',()=>evidenceController?.abort());
$('#restore-session').addEventListener('click',async()=>{const id=window.prompt('Сервер берген session_id енгізіңіз:');if(!id?.trim())return;resetSession();const epoch=state.generation,controller=new AbortController();state.controller=controller;setBusy(true);status('analyzing','RESTORING SESSION');try{const data=await api('/api/session/'+encodeURIComponent(id.trim()),{signal:controller.signal});if(epoch!==state.generation)return;state.result=normalizeResult(data);state.sessionId=id.trim();showResult();activity('Сервер сессиясы қалпына келтірілді');}catch(error){if(epoch===state.generation){status('error','RESTORE FAILED');toast(error.message);}}finally{if(epoch===state.generation){setBusy(false);state.controller=null;}}});
new ResizeObserver(()=>{cancelAnimationFrame(graphFrame);graphFrame=requestAnimationFrame(renderGraph);}).observe($('#neural-stage'));

// 8. CANVAS NEURAL CORE — local procedural artwork; no image asset required.
const canvas=$('#core-canvas'),ctx=canvas.getContext('2d');let lastPaint=0,rotation=0;
const particles=Array.from({length:82},(_,i)=>{const y=1-(i/81)*2,r=Math.sqrt(1-y*y),theta=i*Math.PI*(3-Math.sqrt(5));return{x:Math.cos(theta)*r,y,z:Math.sin(theta)*r};});
function drawCore(time){requestAnimationFrame(drawCore);if(document.hidden||time-lastPaint<40)return;if(!state.motion&&lastPaint)return;lastPaint=time;const dpr=Math.min(devicePixelRatio||1,2),size=canvas.clientWidth;if(!size)return;canvas.width=Math.round(size*dpr);canvas.height=Math.round(size*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size,size);rotation+=root.dataset.state==='analyzing'?.016:.003;const radius=size*.44,points=particles.map(p=>{const x=p.x*Math.cos(rotation)-p.z*Math.sin(rotation),z=p.x*Math.sin(rotation)+p.z*Math.cos(rotation);return{x:size/2+x*radius,y:size/2+p.y*radius,z};});const rgb=root.dataset.state==='error'?'255,100,135':root.dataset.state==='complete'?'0,229,195':'30,195,255';points.forEach((p,i)=>{points.slice(i+1).forEach(q=>{const distance=Math.hypot(p.x-q.x,p.y-q.y);if(distance<size*.18&&Math.abs(p.z-q.z)<.45){ctx.strokeStyle=`rgba(${rgb},${.05+(p.z+1)*.09})`;ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}});ctx.fillStyle=`rgba(${rgb},${.2+(p.z+1)*.35})`;ctx.beginPath();ctx.arc(p.x,p.y,p.z>.1?1.15:.7,0,Math.PI*2);ctx.fill();});}
if(ctx)requestAnimationFrame(drawCore);
function dismissStartup(){$('#startup').classList.add('dismissed');setTimeout(()=>$('#startup').hidden=true,550);}
$('#skip-startup').addEventListener('click',dismissStartup);setTimeout(()=>$('#boot-status').textContent='CONNECTING NEURAL ENGINE',700);setTimeout(()=>$('#boot-status').textContent='SEMANTIC SYSTEM READY',1500);setTimeout(dismissStartup,state.motion?2400:150);
setMotion(state.motion);renderFilters();renderDNA('a');renderDNA('b');activity(DEMO_MODE?'Демо жүйе дайын · құжаттарды қосыңыз':'Agent API режимі · құжаттарды қосыңыз');
if(!DEMO_MODE){$('#demo-button').hidden=true;$('#system-label').textContent='AGENT API / CONNECTION ON REQUEST';$('#readiness-mode').textContent='LIVE API';$('#activity-mode').textContent='AGENT API SESSION';$('#demo-note').textContent='API · файлдар серверге жіберіледі';$('#settings-mode-copy').textContent='Нақты режим: құжаттар Agent API серверіне жіберіледі. Метрикалар серверден алынады. Интерфейс LLM кілттерін сақтамайды. AI қорытындысын бастапқы құжатпен тексеріңіз.';$('#restore-session').hidden=false;$('#boot-ready').textContent='API MODE / READY';document.querySelectorAll('.dna-panel').forEach(el=>el.hidden=true);}


